[bumpver]
current_version = "0.23.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"setup.py" = [
    'version="{version}"',
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"stypes/__init__.py" = [
    '__version__ = "{version}"'
]
